name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  flake-check:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-community
      - name: parse
        run: nix-instantiate --json --parse ./**/*.nix
      - name: flake-check
        run: |
          nix flake check -L
  build-shell:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-community
      - name: build-shell
        run: |
          SYSTEM="$(nix eval --impure --expr 'builtins.currentSystem')"
          nix build -L .\#devShells."$SYSTEM".default.inputDerivation
  build-packages:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-community
      - name: build-packages
        run: |
          SYSTEM="$(nix eval --impure --expr 'builtins.currentSystem')"
          nix build -L .\#packages."$SYSTEM".default
  build-images:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system:
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: nix-community
      - name: build-packages
        run: |
          SYSTEM="$(nix eval --impure --expr 'builtins.currentSystem')"
          nix build -L .\#dockerImages."$SYSTEM".default
